## One initial idea was to use kwoodson.yedit and modify yaml files in place,
## but kustomize is more flexible and we do not have to invent another DSL
#- name: Check kwoodson.yedit role
#  command: ansible-galaxy list kwoodson.yedit
#  register: ret

#- name: Install kwoodson.yedit
#  command: ansible-galaxy install kwoodson.yedit
#  when: "'was not found' not in ret.stdout"

- name: "Check kustomize version (want v{{ kustomize_version }})"
  command: bin/kustomize version
  register: kustomize_check
  ignore_errors: yes

- block:
  - name: Download kustomize
    get_url:
      url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv{{ kustomize_version }}/kustomize_v{{ kustomize_version }}_linux_amd64.tar.gz
      dest: "{{ arangodb_tempdir.path }}/kustomize.tar.gz"
  - name: Extract kustomize
    command: "tar -xzf {{ arangodb_tempdir.path }}/kustomize.tar.gz -C bin/"
  when:
    kustomize_check.rc > 0
    or 'v'~ kustomize_version not in kustomize_check.stdout

- name: Install requirements
  pip:
    extra_args: -U
    name: "{{ item }}"
  loop: "{{ lookup('file', 'requirements.pip').splitlines() }}"
